global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9090']
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus-c3p0"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scrape_interval: 1s # poll very quickly for a more responsive demo
    static_configs:
      - targets: [ "192.168.1.111:5209" ]